import React from "react";
import { useNavigate } from "react-router-dom";

export default function PrivacyScreen() {
  const navigate = useNavigate();

  return (
    <div style={styles.wrapper}>
      <div style={styles.header}>
        <h2 style={styles.title}>Privacy Policy</h2>

        <button style={styles.close} onClick={() => navigate("/")}>
          ✕
        </button>
      </div>

      <div style={styles.container}>
        <p style={styles.date}>Last Updated: March 16, 2026</p>

        <p style={styles.text}>
          This Privacy Policy describes how Ikriskshetra Private Limited
          ("Company", "we", "our", or "us") collects, uses, and protects your
          information when you use the Her Solace mobile application (“App”).
        </p>

        <p style={styles.text}>
          Her Solace is a health and wellness application designed to provide
          informational insights related to hormonal wellness, lifestyle
          patterns, and wellbeing.
        </p>

        <p style={styles.text}>
          By downloading or using the App, you agree to the collection and use
          of information in accordance with this Privacy Policy.
        </p>

        <h3 style={styles.heading}>1. Information We Collect</h3>

        <h4 style={styles.subheading}>Personal Information</h4>

        <p style={styles.text}>
          • Name (optional) <br />
          • Email address <br />
          • Phone number (if used for account verification or security) <br />
          • Age or age range (optional)
        </p>

        <h4 style={styles.subheading}>
          Phone Number for Two-Factor Authentication
        </h4>

        <p style={styles.text}>
          If two-factor authentication (2FA) is enabled for your account, we may
          collect and store your phone number to enhance account security. It
          may be used to send OTP codes and verify your identity. Your phone
          number will not be used for marketing purposes and will never be sold.
        </p>

        <h4 style={styles.subheading}>Health and Wellness Data</h4>

        <p style={styles.text}>
          Users may voluntarily log menstrual cycle information, symptoms, mood
          patterns, energy levels, lifestyle habits, sleep information, and
          journal entries. This data is used only to generate personalized
          insights.
        </p>

        <h4 style={styles.subheading}>Device and Usage Information</h4>

        <p style={styles.text}>
          We may collect device type, operating system, app usage statistics,
          log files, and anonymous analytics data.
        </p>

        <h3 style={styles.heading}>2. How We Use Your Information</h3>

        <p style={styles.text}>
          • Operate and maintain the App <br />
          • Provide personalized wellness insights <br />
          • Generate AI-based informational insights <br />
          • Improve app functionality <br />
          • Respond to support requests <br />
          • Ensure security and prevent fraud
        </p>

        <h3 style={styles.heading}>3. AI-Generated Insights</h3>

        <p style={styles.text}>
          Insights generated by the app are for informational purposes only and
          should not be considered medical advice. Always consult qualified
          healthcare professionals for medical concerns.
        </p>

        <h3 style={styles.heading}>4. Data Storage and Security</h3>

        <p style={styles.text}>
          We implement administrative and technical safeguards to protect user
          data. However, no digital platform can guarantee absolute security.
        </p>

        <h3 style={styles.heading}>5. Data Sharing</h3>

        <p style={styles.text}>
          We do not sell personal data. Limited data may be shared with trusted
          service providers for hosting, analytics, and authentication services.
        </p>

        <h3 style={styles.heading}>6. Data Retention</h3>

        <p style={styles.text}>
          User data is retained only as long as necessary to provide services or
          comply with legal obligations.
        </p>

        <h3 style={styles.heading}>7. User Rights and Account Deletion</h3>

        <p style={styles.text}>
          Users may request account deletion by contacting:
          support@ikriskshetra.com
        </p>

        <h3 style={styles.heading}>8. Children and Teen Users</h3>

        <p style={styles.text}>
          Her Solace is intended for users aged 13 years and older. Users under
          18 should use the App with parental guidance where required.
        </p>

        <h3 style={styles.heading}>9. Third-Party Services</h3>

        <p style={styles.text}>
          The App may integrate third-party services for analytics, hosting, or
          authentication. These services operate under their own privacy
          policies.
        </p>

        <h3 style={styles.heading}>10. Changes to This Policy</h3>

        <p style={styles.text}>
          We may update this policy from time to time with a revised "Last
          Updated" date.
        </p>

        <h3 style={styles.heading}>11. Contact</h3>

        <p style={styles.text}>
          Ikriskshetra Private Limited <br />
          Email: support@ikriskshetra.com
        </p>
      </div>
    </div>
  );
}

const styles = {
  wrapper: {
    height: "100vh",
    display: "flex",
    flexDirection: "column",
  },

  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 20,
  },

  title: {
    fontSize: 22,
    fontWeight: 700,
  },

  close: {
    fontSize: 18,
    cursor: "pointer",
    background: "none",
    border: "none",
  },

  container: {
    padding: 20,
    overflowY: "auto",
  },

  date: {
    marginBottom: 16,
    color: "#666",
  },

  heading: {
    fontSize: 18,
    fontWeight: 700,
    marginTop: 20,
  },

  subheading: {
    fontSize: 16,
    fontWeight: 600,
    marginTop: 10,
  },

  text: {
    fontSize: 14,
    lineHeight: "22px",
    marginTop: 6,
  },
};