import { useNavigate } from 'react-router-dom';

export default function TermsScreen() {
  const navigate = useNavigate();

  return (
    <div style={styles.page}>
      <div style={styles.card}>
        <div style={styles.header}>
          <h2>Terms & Conditions</h2>

          <button style={styles.close} onClick={() => navigate('/welcome')}>
            ✕
          </button>
        </div>

        <div style={styles.content}>
          <p>
            Welcome to Her Solace.
            <br />
            <br />
            By using this application you agree to the following terms:
            <br />
            <br />
            1. This app provides health insights based on menstrual cycle data.
            <br />
            <br />
            2. The information provided in this application is for educational and wellness purposes only.
            <br />
            <br />
            3. The insights generated by the application should not replace professional medical advice, diagnosis, or
            treatment.
            <br />
            <br />
            4. Your data may be stored securely and used to improve the application's performance and user experience.
            <br />
            <br />
            5. Users must be at least 13 years old to use this application. Users under 18 should use the app with
            parental or guardian supervision where required.
            <br />
            <br />
            6. Continued use of the Her Solace application indicates acceptance of these terms.
          </p>
        </div>

        <button style={styles.button} onClick={() => navigate('/welcome')}>
          Close
        </button>
      </div>
    </div>
  );
}

const styles = {
  page: {
    minHeight: '100vh',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    background: '#f6f6f6',
    padding: 20,
  },

  card: {
    width: '100%',
    maxWidth: 700,
    background: '#fff',
    padding: 30,
    borderRadius: 16,
    boxShadow: '0 10px 25px rgba(0,0,0,0.08)',
  },

  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
    marginBottom: 20,
  },

  close: {
    border: 'none',
    background: 'none',
    fontSize: 22,
    cursor: 'pointer',
  },

  content: {
    fontSize: 14,
    lineHeight: 22,
    color: '#333',
  },

  button: {
    marginTop: 25,
    background: '#c08497',
    padding: '12px 20px',
    border: 'none',
    borderRadius: 10,
    color: '#fff',
    cursor: 'pointer',
    fontWeight: 600,
  },
};
